language: go

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database revisioneer;' -U postgres

before_install:
  - sudo apt-get update
  - sudo apt-get install cpanminus perl
  - cpanm --notest --verbose --no-interactive ExtUtils::Depends
  - cpanm --notest --verbose --no-interactive App::Sqitch

after_failure:
  - cat /home/travis/.cpanm/build.log

after_script:
  - cat /home/travis/.cpanm/build.log

go:
  - 1.2
  - tip

install:
  - go get github.com/gorilla/context
  - go get github.com/gorilla/mux
  - go get github.com/lib/pq
  - go get github.com/lib/pq/oid
  - go get github.com/splicers/jet
  - sqitch deploy