language: go

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database revisioneer;' -U postgres

before_install:
  - sudo apt-get update
  - sudo apt-get install cpanminus
  - cpanm --quiet --notest --skip-satisfied --force App::Sqitch

go:
  - 1.2
  - tip

install:
  - go get github.com/gorilla/context
  - go get github.com/gorilla/mux
  - go get github.com/lib/pq
  - go get github.com/lib/pq/oid
  - go get github.com/splicers/jet
  - sqitch deploy